compiler:
    solc:
        optimize: true
        runs: 200
        version: 0.8.17
        remappings:
        - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"
        - '@openzeppelin/contracts-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.5.0/contracts'

dependencies:
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.5.0
  - OpenZeppelin/openzeppelin-contracts@4.5.0
