// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "2ed56dff-a941-4a12-904e-1d75cdfbaae8");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1610645970);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1610645949);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1610645945);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1610646002);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 1909);
user_pref("browser.cache.disk.capacity", 757760);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1610645940);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{678ca1b2-4290-4019-a680-37e30d85d71b}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1610645954775");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1610647779775");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1610645948077");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1610667548077");
user_pref("browser.search.region", "RO");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1610645945");
user_pref("browser.slowStartup.averageTime", 11403);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20200720193547");
user_pref("browser.startup.homepage_override.mstone", "79.0");
user_pref("browser.startup.lastColdStartupCheck", 1610645944);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1610645946795");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "79.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "29caded13a1c4d7e9112e6af85802308");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "79.0");
user_pref("extensions.lastPlatformVersion", "79.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"5d902e6c-e1aa-472c-96a3-8c8b3986e36f\",\"formautofill@mozilla.org\":\"7e1c8336-1cd3-4569-ac18-04860176381a\",\"screenshots@mozilla.org\":\"ebf1fb78-5c18-4c88-9eda-fe8539f9447c\",\"webcompat-reporter@mozilla.org\":\"a60ce6b3-d527-43d9-94df-1de349b46012\",\"webcompat@mozilla.org\":\"0dcdb5d1-098b-4b67-b463-97408e2a783b\",\"default-theme@mozilla.org\":\"9892cb29-092b-409a-9caf-d8ed476d2df3\",\"google@search.mozilla.org\":\"9253e157-5deb-4025-908f-2f61a5a3bfe6\",\"amazondotcom@search.mozilla.org\":\"b316bd86-9b35-430b-bb6a-8b5e6a0fef6c\",\"wikipedia@search.mozilla.org\":\"6878263f-388a-4023-9f95-991cf0adc1bc\",\"bing@search.mozilla.org\":\"aab24185-bcc1-4fc8-8a23-5245b3584da2\",\"ddg@search.mozilla.org\":\"6cc892c7-fb82-4117-8552-57e5df96a372\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "90defb93-c3b1-4c6a-b134-4348ff54ea76");
user_pref("security.sandbox.plugin.tempDirSuffix", "b6e3a9f3-3a2f-47f3-801d-10da34793072");
user_pref("toolkit.startup.last_success", 1610645933);
user_pref("toolkit.telemetry.cachedClientID", "1e20f5ec-3cf9-43ab-af03-ccea42feb1cb");
user_pref("toolkit.telemetry.previousBuildID", "20200720193547");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
