version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    environment:
      mysql_pass: 'REDACTED'
      PUBLIC_KEY: 'REDACTED' # You can add you recaptcha public key here
      PRIVATE_KEY: 'REDACTED' # You can add you recaptcha private key here
    image: justsu
    ports:
      - "80:80"
    depends_on:
      - db
    restart: always
    dns:
      - "127.0.0.11"
      - "8.8.8.8"
    networks:
      - intnet

  db:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'REDACTED'
      MYSQL_DATABASE: 'yogosha'
    dns:
      - "127.0.0.11" 
      - "8.8.8.8"
    restart: always
    networks:
      - intnet

  bot:
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    image: bot
    environment:
      username: 'REDACTED'
      password: 'REDACTED'
      DOMAIN: '34.204.107.224' 
    restart: always
    dns:
      - "127.0.0.11" 
      - "8.8.8.8"
    networks:
      - intnet

networks:
  intnet:
    ipam:
      config:
        - subnet: 172.16.0.0/24
          gateway: 172.16.0.1
