dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.8.0
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.0"
dotenv: .env
networks:
  default: mainnet-fork
  xmas:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}
