name: stakeking
plugins:
  - name: solidity
  - name: alchemy
  - name: foundry
  - name: infura
  - name: etherscan
ethereum:
  default_network: mainnet-fork
  mainnet_fork:
    default_provider: foundry
    gas_limit: auto
    transaction_acceptance_timeout: 180
    default_transaction_type: 0
  mainnet:
    default_provider: alchemy
    transaction_acceptance_timeout: 180
foundry:
  fork:
    ethereum:
      mainnet_fork:
        upstream_provider: alchemy

dependencies:
  - name: openzeppelin-contracts
    github: OpenZeppelin/openzeppelin-contracts
    ref: 4.7.3

solidity:
  version: 0.8.8
  import_remapping:
    - "lib/openzeppelin-contracts/contracts=openzeppelin-contracts/4.7.3"
test:
  mnemonic: test test test test test test test test test test test junk
  number_of_accounts: 10
