name: 100%
plugins:
  - name: solidity
  - name: alchemy
  - name: foundry
  - name: infura
  - name: etherscan
ethereum:
  default_network: mainnet-fork
  mainnet_fork:
    default_provider: foundry
    gas_limit: auto
    transaction_acceptance_timeout: 180
    default_transaction_type: 0
  mainnet:
    default_provider: alchemy
    transaction_acceptance_timeout: 180
foundry:
  host: http://one-hundred-percent.challenges.paradigm.xyz:8545/51470e0c-dfa5-432a-a7c9-bbd5ef6384ba/main
  fork:
    ethereum:
      mainnet_fork:
        upstream_provider: alchemy
dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.2.0
  - name: wighawag
    github: wighawag/clones-with-immutable-args
    version: 1.0.0
    contracts_folder: src
solidity:
  version: 0.8.13
  import_remapping:
    - "@openzeppelin/contracts=OpenZeppelin/4.2.0"
    - "@clones-with-immutable-args=wighawag/1.0.0"

test:
  mnemonic: test test test test test test test test test test test junk
  number_of_accounts: 10
